spring:
  datasource:
    url: jdbc:postgresql://postgres/yuvro
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update
  h2.console.enabled: false